apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{.Values.microserviceName}}-serviceaccount"
  annotations:
    azure.workload.identity/client-id: {{.Values.identityClientId}}
  labels:
    azure.workload.identity/use: "true"
